name: Miscellaneous
version: '${project.version}'
main: misc.utilities.Utilities
api-version: 1.19
authors: [Leo13]
description: A plugin for general purpose (cool stuff).
commands:
  utility:
    description: The main command for the Utilities plugin.
    usage: /<command> reload
    permission: utility.main
  reboot:
    description: Restarts the server after the given time.
    usage: /<command> [time] [reason]
    permission: utility.reboot
permissions:
  utility.main:
    description: Allows you to use the main command for the Utilities plugin.
    default: op
  utility.reboot:
    description: Allows you to restart the server.
    default: op
  utility.doublejump:
    description: Allows players to double jump.
    default: op